---
# fix_debian10_grub_errors/tasks/main.yml

- name: 'Remove grub packages'
  package:
    name: "{{ grub_packages }}"
    state: 'absent'
  when: 'ansible_distribution == "Debian" and ansible_distribution_version == "10"'
  notify:
    - 'Reboot'
    - 'Wait for the machine(s) to be ready again'
